# File generated by Flopy version 3.9.1 on 04/03/2025 at 15:34:00.
BEGIN attributes
  NAMES  rch_2
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00150000
       1.00000000       0.00100000
      11.00000000       0.00150000
      21.00000000       0.00250000
      31.00000000       0.00150000
END timeseries

