# File generated by Flopy version 3.9.1 on 07/28/2025 at 15:10:21.
BEGIN attributes
  NAMES  rch_1
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00160000
       1.00000000       0.00180000
      11.00000000       0.00190000
      21.00000000       0.00160000
      31.00000000       0.00180000
END timeseries

