# File generated by Flopy version 3.9.1 on 04/09/2025 at 10:49:57.
BEGIN attributes
  NAMES  FLOWRATE
  METHODS  LINEAREND
END attributes

BEGIN timeseries
       0.00000000    2000.00000000
     307.00000000    6000.00000000
     791.00000000    5000.00000000
    1000.00000000    9000.00000000
END timeseries

