//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USGS.Puma.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("USGS.Puma.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap CollapsedLegendItem {
            get {
                object obj = ResourceManager.GetObject("CollapsedLegendItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CollapseLegendItem2 {
            get {
                object obj = ResourceManager.GetObject("CollapseLegendItem2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ExpandedLegendItem {
            get {
                object obj = ResourceManager.GetObject("ExpandedLegendItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ExpandLegendItem2 {
            get {
                object obj = ResourceManager.GetObject("ExpandLegendItem2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap MapRolledUpBmp {
            get {
                object obj = ResourceManager.GetObject("MapRolledUpBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ReCenterBmp {
            get {
                object obj = ResourceManager.GetObject("ReCenterBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] ReCenterCur {
            get {
                object obj = ResourceManager.GetObject("ReCenterCur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap SelectArrowBmp {
            get {
                object obj = ResourceManager.GetObject("SelectArrowBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZoomInBmp {
            get {
                object obj = ResourceManager.GetObject("ZoomInBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] ZoomInCur {
            get {
                object obj = ResourceManager.GetObject("ZoomInCur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap ZoomOutBmp {
            get {
                object obj = ResourceManager.GetObject("ZoomOutBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] ZoomOutCur {
            get {
                object obj = ResourceManager.GetObject("ZoomOutCur", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
