# File generated by Flopy version 3.9.1 on 05/04/2025 at 06:01:08.
BEGIN attributes
  NAMES  rch_3
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00160000
       1.00000000       0.00180000
      11.00000000       0.00190000
      21.00000000       0.00160000
      31.00000000       0.00180000
END timeseries

